binds:
- port: 8082
  listeners:
  - protocol: TCP
    name: testdsfsdfaaaaa
    hostname: b.com
    tcpRoutes:
    - name: adsfaaaaaaa
      namespace: sadf
      ruleName: d
    - name: test
      namespace: a
      ruleName: asdfasdf
      hostnames:
      - b.com
    - name: myroute
      hostnames:
      - b.com
  - name: lkjlkjl
    routes:
    - matches:
      - path:
          pathPrefix: /
        method: GET
      backends:
      - weight: 1
        dynamic: {}
      - weight: 53
        policies:
          mcpAuthorization:
            rules:
            - asdf
          backendAuth:
            passthrough: {}
        host: asdf:42
      name: myroute
      ruleName: test
    - matches:
      - path:
          pathPrefix: /
      name: asdfasdfasdf
  tunnelProtocol: direct
- port: 8081
  listeners:
  - protocol: HBONE
    name: asdf
  tunnelProtocol: direct
