binds:
- port: 8080
  listeners:
  - protocol: TCP
    name: testdsfsdfaaaaa
    hostname: b.com
    tcpRoutes:
    - name: adsf
      namespace: sadf
      ruleName: d
    - name: test
      namespace: a
      ruleName: asdfasdf
      hostnames:
      - b.com
    - name: asdfasdfasdfasdfasdf
      hostnames:
      - b.com
  - name: lkjlkjl
    routes:
    - matches:
      - path:
          pathPrefix: /
      name: myroute
      ruleName: test
    - matches:
      - path:
          pathPrefix: /
      name: asdfasdfasdf
  tunnelProtocol: direct
- port: 8081
  listeners:
  - protocol: HBONE
    name: asdf
  tunnelProtocol: direct
