binds:
- port: 8082
  listeners:
  - protocol: TCP
    name: testdsfsdfaaaaa
    hostname: b.com
    tcpRoutes:
    - name: adsf
      namespace: sadf
      ruleName: d
    - name: test
      namespace: a
      ruleName: asdfasdf
      hostnames:
      - b.com
    - name: myroute
      hostnames:
      - b.com
  - name: lkjlkjl
    routes:
    - matches:
      - path:
          pathPrefix: /
      backends:
      - weight: 1
        ai:
          name: asdf
          provider:
            openAI:
              model: gpt-4
          tokenize: false
      - weight: 2
        policies:
          mcpAuthorization:
            rules:
            - asdf
        dynamic: {}
      name: myroute
      ruleName: test
    - matches:
      - path:
          pathPrefix: /
      name: asdfasdfasdf
  tunnelProtocol: direct
- port: 8081
  listeners:
  - protocol: HBONE
    name: asdf
  tunnelProtocol: direct
