binds:
- port: 8082
  listeners:
  - protocol: TCP
    name: testdsfsdfaaaaa
    hostname: b.com
    tcpRoutes:
    - name: adsfaaaaaaa
      namespace: sadf
      ruleName: d
    - name: test
      namespace: a
      ruleName: asdfasdf
      hostnames:
      - b.com
      backends:
      - weight: 1
        service:
          name: test/abc
          port: 123
    - name: myrouteasdf
      hostnames:
      - b.com
  - name: lkjlkjl
    routes:
    - matches:
      - path:
          pathPrefix: /
        method: GET
      backends:
      - weight: 1
        mcp:
          targets:
          - name: asdf
            sse:
              host: aaa
          statefulMode: stateful
          prefixMode: always
      - weight: 53
        policies:
          mcpAuthorization:
            rules:
            - asdf
          backendAuth:
            passthrough: {}
        host: asdf:423
      - weight: 1
        dynamic: {}
      name: myrouteabc
      ruleName: test1233
  tunnelProtocol: direct
- port: 8081
  listeners:
  - protocol: HBONE
    name: asdf
    routes:
    - matches:
      - path:
          pathPrefix: /
      name: testasdf
  tunnelProtocol: direct
- listeners: []
  port: 2222
  tunnelProtocol: direct
- listeners: []
  port: 65535
  tunnelProtocol: hboneGateway
